# Generated by Django 3.1.2 on 2021-08-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frm', models.CharField(max_length=50)),
                ('to', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('timestamp', models.CharField(max_length=50)),
            ],
        ),
    ]
