# Generated by Django 3.1.2 on 2021-08-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payments',
        ),
    ]
